---
# Source: tazama/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tazama-postgres-credentials
  namespace: default
  labels:
    app.kubernetes.io/name: tazama-shared-secrets
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: tazama
type: Opaque
stringData:
  # Configuration database credentials
  CONFIGURATION_DATABASE_USER: "tazama"
  CONFIGURATION_DATABASE_PASSWORD: "postgres"
  
  # Event history database credentials  
  EVENT_HISTORY_DATABASE_USER: "tazama"
  EVENT_HISTORY_DATABASE_PASSWORD: "postgres"
  
  # Evaluation database credentials
  EVALUATION_DATABASE_USER: "tazama"
  EVALUATION_DATABASE_PASSWORD: "postgres"
  
  # Raw history database credentials
  RAW_HISTORY_DATABASE_USER: "tazama"
  RAW_HISTORY_DATABASE_PASSWORD: "postgres"
