---
# Source: tazama/templates/infrastructure/external-services.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    helm.sh/chart: tazama-1.0.0
    app.kubernetes.io/name: tazama
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: database
    infrastructure.tazama.io/type: external
    infrastructure.tazama.io/service: postgres
  annotations:
    infrastructure.tazama.io/external-host: ""
    infrastructure.tazama.io/external-port: "5432"
    infrastructure.tazama.io/ssl-enabled: "true"
spec:
  type: ExternalName
  externalName: 
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
