---
# Source: tazama/templates/typologies/typologies.yaml
apiVersion: v1
kind: Service
metadata:
  name: tazama-typologies
  namespace: default
  labels:
    app: tazama-typologies
    app.kubernetes.io/part-of: tazama
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: typology
